apiVersion: apps/v1
kind: Deployment
metadata:
     name: deploy
     labels:
        app: mydeploy1
        tier: mydeploy2
spec:
    template:
        metadata:
          name: pod-man
          labels:
              app: my-app1
        spec:
            containers:
            - image: arch1250/arch1250:v1
              name: coder
              imagePullPolicy: Always
    replicas: 1
    selector:
        matchLabels:
            app: my-app1
---
apiVersion: v1
kind: Service
metadata:
      name: myservice1
spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
        app: my-app1
